Add ucycles to request messages
cartesi/grpc-interfaces pull request #16
Opened 2023-06-30 09:51 UTC by not4x217

Add ucycles to request messages as part of the work on uarch architecture.

2023-06-30 09:53 UTC, stskeeps commented
OK from Compute side (which is only consumer of that interface)

2023-06-30 09:53 UTC, stskeeps approved these changes

2023-07-13 14:08 UTC, stskeeps approved these changes

2023-07-13 14:15 UTC, diegonehab requested changes
See comment

2023-08-21 19:52 UTC, vfusco commented
Deprecated.

2023-08-21 19:52 UTC, closed without merging