feat: add interpreter break reason in run response
cartesi/grpc-interfaces pull request #28
Opened 2024-01-18 11:31 UTC by edubart

2024-01-18 13:33 UTC, diegonehab commented on cartesi-machine.proto
> +    enum InterpreterBreakReason {
Huh. I didn't even know you could define an enum inside a message. I'd move it out just to make it more similar to the other languages.

2024-02-07 16:43 UTC, diegonehab approved these changes, later dismissed

2024-02-07 18:08 UTC, vfusco requested changes
Please add a changelog ready for v0.16.0 release

2024-02-07 20:53 UTC, vfusco approved these changes

2024-02-07 20:54 UTC, merged